//
//  GeneratedWord.swift
//  Nomi
//
//  Created on December 7, 2025.
//

import Foundation

/// Represents a word generated by AI before it's added to the journal
struct GeneratedWord: Identifiable, Codable {
    let id: UUID
    let targetWord: String
    let romanization: String?
    let englishWord: String
    let exampleSentence: String?
    var stickerImageURL: String?
    var stickerImageData: Data?
    var stickerEmoji: String? // Fallback emoji when no image is available
    
    init(
        id: UUID = UUID(),
        targetWord: String,
        romanization: String? = nil,
        englishWord: String,
        exampleSentence: String? = nil,
        stickerImageURL: String? = nil,
        stickerImageData: Data? = nil,
        stickerEmoji: String? = nil
    ) {
        self.id = id
        self.targetWord = targetWord
        self.romanization = romanization
        self.englishWord = englishWord
        self.exampleSentence = exampleSentence
        self.stickerImageURL = stickerImageURL
        self.stickerImageData = stickerImageData
        self.stickerEmoji = stickerEmoji
    }
}

/// Response from AI word generation
struct WordGenerationResponse: Codable {
    let words: [GeneratedWordData]
}

struct GeneratedWordData: Codable {
    let targetWord: String
    let romanization: String?
    let englishWord: String
    let exampleSentence: String?
    
    enum CodingKeys: String, CodingKey {
        case targetWord = "target_word"
        case romanization
        case englishWord = "english_word"
        case exampleSentence = "example_sentence"
    }
}
